# Generated by Django 4.1.1 on 2023-03-05 10:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0003_alter_create_job_relevent_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_job',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
