# Generated by Django 4.1.1 on 2023-03-05 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0005_apply_job'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Apply_Job',
        ),
    ]
