# Generated by Django 4.1.1 on 2023-03-02 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='career_preference',
            name='monthly_yearly_choice',
            field=models.CharField(blank=True, choices=[('per month', 'per month'), ('per year', 'per year')], max_length=40),
        ),
        migrations.AlterField(
            model_name='career_preference',
            name='min_expected_salary_currency',
            field=models.CharField(blank=True, choices=[('US Dollar', 'US Dollar'), ('Euro', 'Euro'), ('Japanese Yen', 'Japanese Yen'), ('British Pound Sterling', 'British Pound Sterling'), ('Australian Dollar', 'Australian Dollar'), ('Canadian Dollar', 'Canadian Dollar'), ('Swiss Franc', 'Swiss Franc'), ('Chinese Yuan', 'Chinese Yuan'), ('Hong Kong Dollar', 'Hong Kong Dollar'), ('New Zealand Dollar', 'New Zealand Dollar'), ('South Korean Won', 'South Korean Won'), ('Singapore Dollar', 'Singapore Dollar'), ('Swedish Krona', 'Swedish Krona'), ('Norwegian Krone', 'Norwegian Krone'), ('Mexican Peso', 'Mexican Peso'), ('Indian Rupee', 'Indian Rupee'), ('Russian Ruble', 'Russian Ruble'), ('South African Rand', 'South African Rand'), ('Brazilian Real', 'Brazilian Real'), ('Turkish Lira', 'Turkish Lira'), ('Polish Zloty', 'Polish Zloty'), ('Danish Krone', 'Danish Krone'), ('Thai Baht', 'Thai Baht'), ('UAE Dirham', 'UAE Dirham'), ('Pakistani Rupee', 'Pakistani Rupee')], max_length=40),
        ),
    ]
