# Generated by Django 4.1.1 on 2023-03-05 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0004_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='basic_info',
            name='profile_pic',
            field=models.ImageField(default='user.png', upload_to='user_pics'),
        ),
        migrations.DeleteModel(
            name='Profile_Pic',
        ),
    ]
