# Generated by Django 4.1.1 on 2023-03-05 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobseeker', '0005_basic_info_profile_pic_delete_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basic_info',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_basic_info', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='career_preference',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_pref', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contact_details',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_contact_info', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='current_employement',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_employement', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='education',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_education', to=settings.AUTH_USER_MODEL),
        ),
    ]
