# Generated by Django 4.1.1 on 2023-03-05 07:57

from django.db import migrations, models
import jobseeker.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0006_alter_basic_info_user_alter_career_preference_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basic_info',
            name='current_location',
            field=models.CharField(blank=True, choices=[('Australia', 'Australia'), ('Brazil', 'Brazil'), ('Canada', 'Canada'), ('China', 'China'), ('France', 'France'), ('Germany', 'Germany'), ('India', 'India'), ('Indonesia', 'Indonesia'), ('Iran', 'Iran'), ('Italy', 'Italy'), ('Japan', 'Japan'), ('Mexico', 'Mexico'), ('Netherlands', 'Netherlands'), ('Nigeria', 'Nigeria'), ('Pakistan', 'Pakistan'), ('Philippines', 'Philippines'), ('Poland', 'Poland'), ('Russia', 'Russia'), ('Saudi Arabia', 'Saudi Arabia'), ('South Africa', 'South Africa'), ('South Korea', 'South Korea'), ('Spain', 'Spain'), ('Sweden', 'Sweden'), ('Switzerland', 'Switzerland'), ('Taiwan', 'Taiwan'), ('Thailand', 'Thailand'), ('Turkey', 'Turkey'), ('Ukraine', 'Ukraine'), ('United Arab Emirates', 'United Arab Emirates'), ('United Kingdom', 'United Kingdom'), ('United States', 'United States'), ('Algeria', 'Algeria'), ('Argentina', 'Argentina'), ('Bangladesh', 'Bangladesh'), ('Belgium', 'Belgium'), ('Colombia', 'Colombia'), ('Egypt', 'Egypt'), ('Iraq', 'Iraq'), ('Kazakhstan', 'Kazakhstan'), ('Malaysia', 'Malaysia'), ('Morocco', 'Morocco'), ('Myanmar', 'Myanmar'), ('Peru', 'Peru'), ('Romania', 'Romania'), ('South Sudan', 'South Sudan'), ('Tanzania', 'Tanzania'), ('Uganda', 'Uganda'), ('Uzbekistan', 'Uzbekistan'), ('Venezuela', 'Venezuela'), ('Vietnam', 'Vietnam'), ('Other', 'Other')], default='Select', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='basic_info',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basic_info',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='basic_info',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='basic_info',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='basic_info',
            name='level_of_english_language',
            field=models.CharField(blank=True, choices=[('Native', 'Native'), ('Fluent', 'Fluent'), ('Working Knowledge', 'Working Knowledge')], default='Fluent', max_length=17, null=True),
        ),
        migrations.AlterField(
            model_name='basic_info',
            name='name_of_city_currently_based',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='basic_info',
            name='passport_country',
            field=models.CharField(blank=True, choices=[('Australia', 'Australia'), ('Brazil', 'Brazil'), ('Canada', 'Canada'), ('China', 'China'), ('France', 'France'), ('Germany', 'Germany'), ('India', 'India'), ('Indonesia', 'Indonesia'), ('Iran', 'Iran'), ('Italy', 'Italy'), ('Japan', 'Japan'), ('Mexico', 'Mexico'), ('Netherlands', 'Netherlands'), ('Nigeria', 'Nigeria'), ('Pakistan', 'Pakistan'), ('Philippines', 'Philippines'), ('Poland', 'Poland'), ('Russia', 'Russia'), ('Saudi Arabia', 'Saudi Arabia'), ('South Africa', 'South Africa'), ('South Korea', 'South Korea'), ('Spain', 'Spain'), ('Sweden', 'Sweden'), ('Switzerland', 'Switzerland'), ('Taiwan', 'Taiwan'), ('Thailand', 'Thailand'), ('Turkey', 'Turkey'), ('Ukraine', 'Ukraine'), ('United Arab Emirates', 'United Arab Emirates'), ('United Kingdom', 'United Kingdom'), ('United States', 'United States'), ('Algeria', 'Algeria'), ('Argentina', 'Argentina'), ('Bangladesh', 'Bangladesh'), ('Belgium', 'Belgium'), ('Colombia', 'Colombia'), ('Egypt', 'Egypt'), ('Iraq', 'Iraq'), ('Kazakhstan', 'Kazakhstan'), ('Malaysia', 'Malaysia'), ('Morocco', 'Morocco'), ('Myanmar', 'Myanmar'), ('Peru', 'Peru'), ('Romania', 'Romania'), ('South Sudan', 'South Sudan'), ('Tanzania', 'Tanzania'), ('Uganda', 'Uganda'), ('Uzbekistan', 'Uzbekistan'), ('Venezuela', 'Venezuela'), ('Vietnam', 'Vietnam'), ('Other', 'Other')], default='Select', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='career_preference',
            name='first_place',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='career_preference',
            name='min_expected_salary_currency',
            field=models.CharField(blank=True, choices=[('US Dollar', 'US Dollar'), ('Euro', 'Euro'), ('Japanese Yen', 'Japanese Yen'), ('British Pound Sterling', 'British Pound Sterling'), ('Australian Dollar', 'Australian Dollar'), ('Canadian Dollar', 'Canadian Dollar'), ('Swiss Franc', 'Swiss Franc'), ('Chinese Yuan', 'Chinese Yuan'), ('Hong Kong Dollar', 'Hong Kong Dollar'), ('New Zealand Dollar', 'New Zealand Dollar'), ('South Korean Won', 'South Korean Won'), ('Singapore Dollar', 'Singapore Dollar'), ('Swedish Krona', 'Swedish Krona'), ('Norwegian Krone', 'Norwegian Krone'), ('Mexican Peso', 'Mexican Peso'), ('Indian Rupee', 'Indian Rupee'), ('Russian Ruble', 'Russian Ruble'), ('South African Rand', 'South African Rand'), ('Brazilian Real', 'Brazilian Real'), ('Turkish Lira', 'Turkish Lira'), ('Polish Zloty', 'Polish Zloty'), ('Danish Krone', 'Danish Krone'), ('Thai Baht', 'Thai Baht'), ('UAE Dirham', 'UAE Dirham'), ('Pakistani Rupee', 'Pakistani Rupee')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='career_preference',
            name='monthly_yearly_choice',
            field=models.CharField(blank=True, choices=[('per month', 'per month'), ('per year', 'per year')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='career_preference',
            name='second_place',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='career_preference',
            name='third_place',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='contact_details',
            name='actual_number',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[jobseeker.models.only_integer]),
        ),
        migrations.AlterField(
            model_name='contact_details',
            name='area_code',
            field=models.CharField(blank=True, default='Select', max_length=10, null=True, validators=[jobseeker.models.only_integer]),
        ),
        migrations.AlterField(
            model_name='contact_details',
            name='counrty_code',
            field=models.CharField(blank=True, choices=[('Australia', '+61'), ('Brazil', '+55'), ('Canada', '+1'), ('China', '+86'), ('France', '+33'), ('Germany', '+49'), ('India', '+91'), ('Indonesia', '+62'), ('Iran', '+98'), ('Italy', '+39'), ('Japan', '+81'), ('Mexico', '+52'), ('Netherlands', '+31'), ('Nigeria', '+234'), ('Pakistan', '+92'), ('Philippines', '+63'), ('Poland', '+48'), ('Russia', '+7'), ('Saudi Arabia', '+966'), ('South Africa', '+27'), ('South Korea', '+82'), ('Spain', '+34'), ('Sweden', '+46'), ('Switzerland', '+41'), ('Taiwan', '+886'), ('Thailand', '+66'), ('Turkey', '+90'), ('Ukraine', '+380'), ('United Arab Emirates', '+971'), ('United Kingdom', '+44'), ('United States', '+1'), ('Algeria', '+213'), ('Argentina', '+54'), ('Bangladesh', '+880'), ('Belgium', '+32'), ('Colombia', '+57'), ('Egypt', '+20'), ('Iraq', '+964'), ('Kazakhstan', '+7'), ('Malaysia', '+60'), ('Morocco', '+212'), ('Myanmar', '+95'), ('Peru', '+51'), ('Romania', '+40'), ('South Sudan', '+211'), ('Tanzania', '+255'), ('Uganda', '+256'), ('Uzbekistan', '+998'), ('Venezuela', '+58'), ('Vietnam', '+84')], default='Select', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contact_details',
            name='type',
            field=models.CharField(blank=True, choices=[('Home', 'Home'), ('Work', 'Work'), ('Mobile', 'Mobile'), ('Other', 'Other')], default='Other', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='current_employement',
            name='activity_of_company',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='current_employement',
            name='current_position',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='current_employement',
            name='experience',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='current_employement',
            name='job_category',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='current_employement',
            name='name_of_company',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='subject_in_university',
            field=models.CharField(blank=True, choices=[('Accounting', 'Accounting'), ('Art History', 'Art History'), ('Biology', 'Biology'), ('Business Administration', 'Business Administration'), ('Chemistry', 'Chemistry'), ('Civil Engineering', 'Civil Engineering'), ('Computer Science', 'Computer Science'), ('Economics', 'Economics'), ('Education', 'Education'), ('Electrical Engineering', 'Electrical Engineering'), ('English Literature', 'English Literature'), ('Environmental Science', 'Environmental Science'), ('Finance', 'Finance'), ('Graphic Design', 'Graphic Design'), ('History', 'History'), ('International Relations', 'International Relations'), ('Journalism', 'Journalism'), ('Marketing', 'Marketing'), ('Mathematics', 'Mathematics'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Music', 'Music'), ('Nursing', 'Nursing'), ('Philosophy', 'Philosophy'), ('Physics', 'Physics'), ('Political Science', 'Political Science'), ('Psychology', 'Psychology'), ('Sociology', 'Sociology'), ('Statistics', 'Statistics'), ('Theater', 'Theater'), ('Visual Arts', 'Visual Arts'), ('Other/No University', 'Other/No University')], default='Select', max_length=100, null=True),
        ),
    ]
