# Generated by Django 4.1.1 on 2023-03-05 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0006_delete_apply_job'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobseeker', '0008_alter_basic_info_user_alter_career_preference_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply_Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField()),
                ('cv', models.FileField(upload_to='')),
                ('applier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applier', to=settings.AUTH_USER_MODEL)),
                ('job_applied', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_appled', to='employer.create_job')),
            ],
        ),
    ]
